### ISSUE TITLE
scansearchresultexport internal server error

### ISSUE THREAD

**Issue by bcoles** [smicallef/spiderfoot#400]
`IndexError: list index out of range` when a search term is entered, then attempting to export:

```
[06/Oct/2019:21:00:09] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/Desktop/spiderfoot/sfwebui.py", line 187, in scansearchresultexport
    parser.writerow([row[0], str(row[10]), str(row[3]), str(row[2]), row[13], datafield])
IndexError: list index out of range
[06/Oct/2019:21:00:09] HTTP 
Request Headers:
  CONNECTION: keep-alive
  REFERER: http://127.0.0.1:5001/scaninfo?id=87B3D633
  HOST: 127.0.0.1:5001
  UPGRADE-INSECURE-REQUESTS: 1
  Remote-Addr: 127.0.0.1
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
127.0.0.1 - - [06/Oct/2019:21:00:09] "GET /scansearchresultexport?id=87B3D633&eventType=&value=<redacted> HTTP/1.1" 500 1615 "http://127.0.0.1:5001/scaninfo?id=87B3D633" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
```

`TypeError: 'NoneType' object is not iterable` when no search term was entered (ie, press enter on an empty search text box, then click export):

```
127.0.0.1 - - [06/Oct/2019:21:18:58] "POST /search HTTP/1.1" 200 31668 "http://127.0.0.1:5001/scaninfo?id=87B3D633" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
[06/Oct/2019:21:18:59] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/Desktop/spiderfoot/sfwebui.py", line 183, in scansearchresultexport
    for row in data:
TypeError: 'NoneType' object is not iterable
[06/Oct/2019:21:18:59] HTTP 
Request Headers:
  CONNECTION: keep-alive
  REFERER: http://127.0.0.1:5001/scaninfo?id=87B3D633
  HOST: 127.0.0.1:5001
  UPGRADE-INSECURE-REQUESTS: 1
  Remote-Addr: 127.0.0.1
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
127.0.0.1 - - [06/Oct/2019:21:18:59] "GET /scansearchresultexport?id=87B3D633&eventType=&value= HTTP/1.1" 500 1555 "http://127.0.0.1:5001/scaninfo?id=87B3D633" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
```

**Comment by smicallef** [comment]
I assume this is because you tried to export an empty search result? I just pushed a fix for that scenario but let me know if this was for something else.

**Comment by bcoles** [comment]
There are two scenarios.

When a search term is entered, and the export functionality is invoked, results in `IndexError: list index out of range`.

When an empty search term is entered (ie, press enter in the search field), and the export functionality is invoked, results in `TypeError: 'NoneType' object is not iterable`.

**Comment by smicallef** [comment]
Are you still getting this now since I pushed the last change?

**Comment by bcoles** [comment]
> 
> 
> Are you still getting this now since I pushed the last change?

The most recent change checks for `None` which prevents the stacktrace, but does not resolve the issue. A search for nothing returns all results. It is expected that exporting the result of the search will still work. Instead, the response from the server is empty, and there is no prompt to download the exported results.

The other issue `IndexError: list index out of range` remains.

**Comment by bcoles** [comment]
![empty response](https://user-images.githubusercontent.com/434827/66333319-70dc0b00-e982-11e9-9797-868cd0353253.png)

**Comment by smicallef** [comment]
I believe I fixed this some time ago and forgot to close. Either way, I can't reproduce it so assume it's fixed :) Please re-open if it's not.

**Comment by bcoles** [comment]
Looks like this is fixed
